// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: protobuf/reading.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Reading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicates if it is the start of a move : *bool|bool|bool
	IsStartMove bool `protobuf:"varint,1,opt,name=isStartMove,proto3" json:"isStartMove,omitempty"`
	// To identify the clients : *string|str|string
	ClientID string `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	// Position of client : int32, int, int32
	ClientPos int32 `protobuf:"varint,3,opt,name=clientPos,proto3" json:"clientPos,omitempty"`
	// Accelerometer X Axis value : *float64|float|double
	AccX float64 `protobuf:"fixed64,4,opt,name=accX,proto3" json:"accX,omitempty"`
	// Accelerometer Y Axis value : *float64|float|double
	AccY float64 `protobuf:"fixed64,5,opt,name=accY,proto3" json:"accY,omitempty"`
	// Accelerometer Z Axis value : *float64|float|double
	AccZ float64 `protobuf:"fixed64,6,opt,name=accZ,proto3" json:"accZ,omitempty"`
	// Gyroscope X Axis value : *float64|float|double
	GyroX float64 `protobuf:"fixed64,7,opt,name=gyroX,proto3" json:"gyroX,omitempty"`
	// Gyroscope Y Axis value : *float64|float|double
	GyroY float64 `protobuf:"fixed64,8,opt,name=gyroY,proto3" json:"gyroY,omitempty"`
	// Gyroscope Z Axis value : *float64|float|double
	GyroZ float64 `protobuf:"fixed64,9,opt,name=gyroZ,proto3" json:"gyroZ,omitempty"`
	// Timestamp in unix nanoseconds : *int64|int/long/int64
	TimeStamp int64 `protobuf:"varint,10,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *Reading) Reset() {
	*x = Reading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_reading_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_reading_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_protobuf_reading_proto_rawDescGZIP(), []int{0}
}

func (x *Reading) GetIsStartMove() bool {
	if x != nil {
		return x.IsStartMove
	}
	return false
}

func (x *Reading) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *Reading) GetClientPos() int32 {
	if x != nil {
		return x.ClientPos
	}
	return 0
}

func (x *Reading) GetAccX() float64 {
	if x != nil {
		return x.AccX
	}
	return 0
}

func (x *Reading) GetAccY() float64 {
	if x != nil {
		return x.AccY
	}
	return 0
}

func (x *Reading) GetAccZ() float64 {
	if x != nil {
		return x.AccZ
	}
	return 0
}

func (x *Reading) GetGyroX() float64 {
	if x != nil {
		return x.GyroX
	}
	return 0
}

func (x *Reading) GetGyroY() float64 {
	if x != nil {
		return x.GyroY
	}
	return 0
}

func (x *Reading) GetGyroZ() float64 {
	if x != nil {
		return x.GyroZ
	}
	return 0
}

func (x *Reading) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

var File_protobuf_reading_proto protoreflect.FileDescriptor

var file_protobuf_reading_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x72, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x81, 0x02, 0x0a,
	0x07, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x63, 0x58, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x61, 0x63, 0x63, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x63, 0x59,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x61, 0x63, 0x63, 0x59, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x63, 0x63, 0x5a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x61, 0x63, 0x63, 0x5a,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x79, 0x72, 0x6f, 0x58, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x67, 0x79, 0x72, 0x6f, 0x58, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x79, 0x72, 0x6f, 0x59, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x67, 0x79, 0x72, 0x6f, 0x59, 0x12, 0x14, 0x0a, 0x05,
	0x67, 0x79, 0x72, 0x6f, 0x5a, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x67, 0x79, 0x72,
	0x6f, 0x5a, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x51,
	0x7a, 0x53, 0x47, 0x2f, 0x6c, 0x61, 0x70, 0x69, 0x73, 0x2d, 0x75, 0x6e, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobuf_reading_proto_rawDescOnce sync.Once
	file_protobuf_reading_proto_rawDescData = file_protobuf_reading_proto_rawDesc
)

func file_protobuf_reading_proto_rawDescGZIP() []byte {
	file_protobuf_reading_proto_rawDescOnce.Do(func() {
		file_protobuf_reading_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_reading_proto_rawDescData)
	})
	return file_protobuf_reading_proto_rawDescData
}

var file_protobuf_reading_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_reading_proto_goTypes = []interface{}{
	(*Reading)(nil), // 0: pb.Reading
}
var file_protobuf_reading_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_reading_proto_init() }
func file_protobuf_reading_proto_init() {
	if File_protobuf_reading_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_reading_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_reading_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_reading_proto_goTypes,
		DependencyIndexes: file_protobuf_reading_proto_depIdxs,
		MessageInfos:      file_protobuf_reading_proto_msgTypes,
	}.Build()
	File_protobuf_reading_proto = out.File
	file_protobuf_reading_proto_rawDesc = nil
	file_protobuf_reading_proto_goTypes = nil
	file_protobuf_reading_proto_depIdxs = nil
}
