// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SensorClient is the client API for Sensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorClient interface {
	// Sends a greeting
	ReadingStream(ctx context.Context, opts ...grpc.CallOption) (Sensor_ReadingStreamClient, error)
}

type sensorClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorClient(cc grpc.ClientConnInterface) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) ReadingStream(ctx context.Context, opts ...grpc.CallOption) (Sensor_ReadingStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sensor_serviceDesc.Streams[0], "/pb.Sensor/ReadingStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorReadingStreamClient{stream}
	return x, nil
}

type Sensor_ReadingStreamClient interface {
	Send(*Reading) error
	Recv() (*Reply, error)
	grpc.ClientStream
}

type sensorReadingStreamClient struct {
	grpc.ClientStream
}

func (x *sensorReadingStreamClient) Send(m *Reading) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorReadingStreamClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorServer is the server API for Sensor service.
// All implementations must embed UnimplementedSensorServer
// for forward compatibility
type SensorServer interface {
	// Sends a greeting
	ReadingStream(Sensor_ReadingStreamServer) error
	mustEmbedUnimplementedSensorServer()
}

// UnimplementedSensorServer must be embedded to have forward compatible implementations.
type UnimplementedSensorServer struct {
}

func (UnimplementedSensorServer) ReadingStream(Sensor_ReadingStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadingStream not implemented")
}
func (UnimplementedSensorServer) mustEmbedUnimplementedSensorServer() {}

// UnsafeSensorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServer will
// result in compilation errors.
type UnsafeSensorServer interface {
	mustEmbedUnimplementedSensorServer()
}

func RegisterSensorServer(s *grpc.Server, srv SensorServer) {
	s.RegisterService(&_Sensor_serviceDesc, srv)
}

func _Sensor_ReadingStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServer).ReadingStream(&sensorReadingStreamServer{stream})
}

type Sensor_ReadingStreamServer interface {
	Send(*Reply) error
	Recv() (*Reading, error)
	grpc.ServerStream
}

type sensorReadingStreamServer struct {
	grpc.ServerStream
}

func (x *sensorReadingStreamServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorReadingStreamServer) Recv() (*Reading, error) {
	m := new(Reading)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sensor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadingStream",
			Handler:       _Sensor_ReadingStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/reading.proto",
}
